### ISSUE TITLE
Chrome65で動作しなくなる

### ISSUE THREAD

**Issue by t-f-m** [hkuno9000/KanColle-YPS#125]
Google Chrome 65.0.3325.146 に更新してから、動作しなくなりました。
厳密に言うと動作はしているのですが、母港画面が機能しません。

devtools の devtools 立ち上げて確認したところ、 $pcDateTime が Date型になっていなくて怒られているようです。
自分の環境だけの話ならいいのですが、念の為報告しておきます。

今のところ、2007行目を修正して動くようにしてます。
https://github.com/hkuno9000/KanColle-YPS/blob/5152be518e5b55d5a6db65c34c55801b1fc6f81a/devtools.js#L2007

これを
```
			var ms = d.getTime() - $pcDateTime.getTime();
```
こう。
```
			var ms = d.getTime() - (new Date($pcDateTime)).getTime();
```

前後も。

```
		if (mission_end > 0) {
			var d = new Date(mission_end);
			var ms = d.getTime() - $pcDateTime.getTime();
			var rest = ms > 0 ? '残' + msec_name(ms) : '終了';
			var id = deck.api_mission[1];
			req.push('遠征' + id + ' ' + $mst_mission[id].api_name + ': ' + d.toLocaleString() + '(' + rest + ')');
			$last_mission[f_id] = '前回遠征: ' + $mst_mission[id].api_name; // 支援遠征では /api_req_mission/result が来ないので、ここで事前更新しておく.
		}
```

Chrome自体の inspector.js も似たようなエラー吐いてるので早晩修正されそうだなとは思いますが、ひとまず報告まで。

**Comment by hkuno9000** [comment]
@t-f-m Chrome65への暫定修正完了です。お試しください。

**Comment by t-f-m** [comment]
無事動作していることを確認しました。ありがとうございます。
