### ISSUE TITLE
sync不可能なケースで任務リストの判定がおかしくなる

### ISSUE THREAD

**Issue by t-f-m** [hkuno9000/KanColle-YPS#139]
Androidアプリ版等のsync不可能な環境で任務をクリアした場合、
「任務リスト(全All)を先頭から最終ページまでめくって、内容を更新してください」の表示が消えなくなる。

**Comment by hkuno9000** [comment]
ブラウザを落として、再起動すると直りませんか？

任務リストのJSONデータがページ単位でしか取れないのが根本的な原因なので、
JSON構造の改修があるかもしれないBLOCK2まで様子見したいです。

任務クリア日時の sync および、未達成の単発任務の消去については、別途対策を検討しています。

**Comment by t-f-m** [comment]
挙動確認しました。再起動で一時的に治るように見えるのですが、その後何らかの任務をクリアすると再び「任務リスト(全All)を先頭から最終ページまでめくって、内容を更新してください」の表示が消えなくなります（今回はウィークリー任務のクリアでの再発生を確認しました）。
デイリー任務でもその日のうち、マンスリー任務でもその月のうちに
「YPS環境でログイン＆任務一覧更新→YPS外環境で任務クリア→YPS環境で任務更新→YPS環境で任務クリア」
の手順を踏めば同様の現象を確認できるかと思います。
