### ISSUE TITLE
HTML5-BLOCK1 海域リセットに伴う敵編成変更対応

### ISSUE THREAD

**Issue by t-f-m** [hkuno9000/KanColle-YPS#140]
海域リセットに伴い、敵艦隊の編成も大幅に変更されており、Kancolle-YPSで蓄積してきた敵編成の情報との食い違いが発生している。
しかし運営アナウンスにもあるように、中部海域全域を主としてリセットされていない海域も存在しており、既存の敵編成情報自体は、依然としてある程度は有効である。

特定の敵編成情報のみ削除するような機能があれば良いのではないかと思われる。
自動での判定は難しそうなので手動で。

\#\#\# 余談ながら、以前からChromeの反応が悪い状態のときに敵編成の記録がズレることがたびたび発生していたので、それの対策にもなりそう

**Comment by hkuno9000** [comment]
敵編成情報 $enemy_db[] については
* 過去のイベント海域の削除
* YPS不具合により残留したゴミの削除
* データのインポート・エクスポート機能対応
も課題です。
私は、devtoolコンソールから直接編集して対処していますが、UI含めてどうしたものか。。

**Comment by hkuno9000** [comment]
海域リセット前（一期）の敵艦隊構成を表示しないようにしました。
海域リセット後（二期）も敵艦隊構成が同じならば、その遭遇カウンタを二期の敵艦隊データにマージして表示します。
