### ISSUE TITLE
建造時の資材増減数が反映されていない

### ISSUE THREAD

**Issue by t-f-m** [hkuno9000/KanColle-YPS#142]
建造時に返ってくるパケットに変更があったようです。
/api_req_kousyou/createship 後に /api_get_member/kdock は返ってきますが、 /api_get_member/material は返ってこないようになっています。

**Comment by hkuno9000** [comment]
@t-f-m 修正してpushしました.

WebStore版の更新は、道中の非戦闘マスのメッセージ修正後に行います。
イベント用のメッセージが出るマスに出会ったら /api_req_map/next のJSONをコピーして、
#141 に貼り付けていただけると助かります。
HTML5版では JSON にメッセージが入っていると思われる節があるので。
