### ISSUE TITLE
Fletcher改造ツリーの解析にて無限ループ発生.

### ISSUE THREAD

**Issue by sion677** [hkuno9000/KanColle-YPS#157]
2020年5月20日のメンテナンス後デベロッパーツールを起動していても、ロードが完了しなくなりました。

**Comment by hkuno9000** [comment]
調査中です

**Comment by sion677** [comment]
修正したとのことですが、再度起動してもロード完了しないのですが・・・

**Comment by hkuno9000** [comment]
@sion677 
ロード完了しないとのことですが、YPSのバージョンは次のどちらになっていますか？
修正版は２です。
1. KanColle-YPS v2.1.20 デッキビルダー対応、比叡改二丙特殊攻撃対応
2. KanColle-YPS v2.1.21 Fletcherコンバート改装艦種ID対応

Google側の審査に通らないと、WebStore版は更新がかからないので
緊急ならば開発版を使ってください。開発版のインストール方法は　https://hkuno9000.github.io/KanColle-YPS/　に解説あります。

**Comment by sion677** [comment]
対処できました。ありがとうございました。
