### ISSUE TITLE
「Service Worker （無効） 」が発生し、プラグインが動作しない

### ISSUE THREAD

**Issue by hkuno9000** [hkuno9000/KanColle-YPS#180]
「Service Worker （無効） 」が発生し、プラグインが動作しなくなった。

![image](https://user-images.githubusercontent.com/6072917/209912710-e9d2e55f-71b1-4b91-97e2-8b8970cab211.png)

**Comment by t-f-m** [comment]
自分も同じ現象に遭遇しました。とりいそぎ、拡張機能のオンオフ、艦これのタブを閉じて新規タブで動かす、の2点試したところ動作する状態に戻せました。

**Comment by hkuno9000** [comment]
@t-f-m 上記の修正コミットおよび #181 の設定変更により、私の環境(Ubuntu22.04+Chrome108)では回避できました。
修正内容の技術的説明はこれです↓
 https://groups.google.com/a/chromium.org/g/chromium-extensions/c/lLb3EJzjw0o/m/cBuC_OJ7AQAJ
