### ISSUE TITLE
出撃戦闘後の艦隊情報の更新不能(ship2廃止、ship_deck対応)

### ISSUE THREAD

**Issue by yamagen75** [hkuno9000/KanColle-YPS#31]
出撃戦闘後の艦隊情報の更新がされなくなったように思います。
艦これAPIの仕様が変更されているようです。
私が確認出来た範囲では、ship2がship_deckになっているのではないかと思いました。
確認をお願いします。

**Comment by hkuno9000** [comment]
5/25メンテで変更されたようですね。解析着手します。

/api_get_member/ship_deck
svdata={
 "api_result":1,
 "api_result_msg":"成功f",
 "api_data":{
   "api_ship_data":[  // 出撃中の艦データ.
      {
       "api_id":44, 
       "api_sortno":192,
       "api_ship_id":192,
       "api_lv":73,
       "api_exp":[299437,7963,28],
       "api_nowhp":56,
       "api_maxhp":56,
       "api_leng":2,
       "api_slot":[20752,7283,7985,20718,-1],
       "api_onslot":[2,2,4,4,0],
       "api_kyouka"[30,50,50,30,0],
       "api_backs":6,
       "api_fuel":36,
       "api_bull":60,
       "api_slotnum":4,
       "api_ndock_time":0,
       "api_ndock_item":[0,0],
       "api_srate":4,
       "api_cond":64,
       "api_karyoku":[99,80],
       "api_raisou":[84,84],
       "api_taiku":[90,83],
       "api_soukou":[78,78],
       "api_kaihi":[72,83],
       "api_taisen":[1,0],
       "api_sakuteki":[52,60],
       "api_lucky":[18,70],
       "api_locked":1,
       "api_locked_equip":1
    },
   {
      "api_id":169,
      "api_sortno":195,
      "api_ship_id":195,
      "api_lv":87,
      "api_exp":[495982,13018,25],
      "api_nowhp":32,
      "api_maxhp":32,
         ～～～中略～～～
    }
  ],
  "api_deck_data":[
    {
       "api_member_id":xxxxxx,
       "api_id":1,
       "api_name":"艦隊名",
       "api_name_id":"xxxxxx",
       "api_mission":[0,0,0,0],
       "api_flagship":"0",
       "api_ship":[292,44,247,245,169,12400]
  }
 ]
}
}

**Comment by hkuno9000** [comment]
対応完了。慣熟テストが必要。

**Comment by yamagen75** [comment]
進撃時の艦隊情報、更新されるようになりました。
早速のご対応ありがとうございます。

**Comment by hkuno9000** [comment]
艦隊情報は更新できているが、保有艦リストが更新されていなかったので、
さらなる修正が必要となる。

**Comment by hkuno9000** [comment]
母港に戻るまでドロップ艦が持つ装備が装備リストに反映されない、という問題は残った。

**Comment by hkuno9000** [comment]
装備リスト反映については良いアイデアがないので、已む無しとして本件はクローズする。

**Comment by t-f-m** [comment]
泥臭いですがこういうことをするのが落とし所になりそうです。
http://nekokan333.blog.fc2.com/blog-entry-375.html

**Comment by hkuno9000** [comment]
ご紹介の対策を仮実装して、ブランチ kaizen31 に push しました。
装備数の初期値テーブル $init_newship_slots は未完成です。
ぼちぼち作業を進めますが、pull request 歓迎します。

**Comment by hkuno9000** [comment]
* wikiの情報を使い、装備数DB newship.js を完成させた.
* ブランチ kaizen31 を master にマージしたので、このトピックを閉じる.

**Comment by hkuno9000** [comment]
装備数DBを完成させただけで、道中表示の装備数更新を忘れていたので、上記commitで修正しました。
これで完成です。
