### ISSUE TITLE
横幅の足りない環境だと装備欄が改行されすぎて悲惨なことになる

### ISSUE THREAD

**Issue by t-f-m** [hkuno9000/KanColle-YPS#42]
画像の通りです。
![24](https://cloud.githubusercontent.com/assets/610464/8973212/6a8b51e4-369d-11e5-97b7-76381ee1cc3e.png)

装備名（とコンマ）ごとに nobr タグで挟みたいです。
関連コード見た感じcontent.js側もいじりそうですがこっちはできれば自分ではあんまり触りたくないのでissueにしました。

**Comment by hkuno9000** [comment]
単語境界のみ折り返し可能としたいところです。
CSS指定でなんとかできないか調べてみます。 
IE なら word-wrap: break-word, word-break: keep-all が使えそうです。

**Comment by hkuno9000** [comment]
対策完了です。
かなり強引なコーディングなので副作用が心配。

**Comment by t-f-m** [comment]
対応ありがとうございます、使ってみた感じでは大きな問題はなさそうです。

**Comment by hkuno9000** [comment]
対応方法とコーディングをやり直しました。
nobr のかわりに wbr を埋め込みます。その対象も td 要素内に限定しました。
また ": "も折り返し対象に追加しました。
