### ISSUE TITLE
BUGFIX: 週間収支の週初データが保存されない場合がある

### ISSUE THREAD

**Issue by hkuno9000** [hkuno9000/KanColle-YPS#44]
yamagen75 commented on commit hkuno9000/KanColle-YPS@b177feedee
実装中、気が付いたので報告です。 週初めに monday_material に now のコピーを保持した時、save_weekly() を 実行しておく必要があるかと思います。 理由は、あ号作戦を遂行中で出撃しないと monday_material が保存されないと思われるからです。

**Comment by hkuno9000** [comment]
@yamagen75
対応完了しました。

**Comment by yamagen75** [comment]
早速の対応ありがとうございます。
今週は、すでに値が保持されているので、来週、確認出来ればと思います。

**Comment by yamagen75** [comment]
今日、週初めの資材量の保存がされていることを確認しました。
出撃していないので、あ号任務も出ていないですが、週間収支が残っているので問題無いかと思います。
確認が遅くなってしまって申し訳ないです。

**Comment by hkuno9000** [comment]
確認ありがとうございました。
