### ISSUE TITLE
2015夏イベント導入の補強増設で増設されたスロットについて

### ISSUE THREAD

**Issue by yamagen75** [hkuno9000/KanColle-YPS#45]
補強増設のアイテムを使って増設したスロットの装備内容を表示したいと思い、５番目のスロットになるのかなとか思って、いろいろ試してみたのですが、どうも違うみたいです。
あと、戦闘時に応急修理要員、応急修理女神の所持数を表示している部分や発動した時の表示など、修正が多岐に渡るような気がしたので、こちらに追加した次第です。
一応、増設されたスロットには、応急修理要員、応急修理女神、戦闘糧食の３種類のみ装備出来ます。

追伸、api_ship に api_slot_ex というプロパティがあるみたいです。

**Comment by hkuno9000** [comment]
補強増設は、実際に使ってみてテストが必要なので対応を躊躇していました。
遭遇回数記録の甲乙丙難易度対応に問題が見つかったので、そちらを先に修正中です。

### 対応
補強増設の装備は JSON上では別プロパティだが、KanColle-YPSとしては特別扱いせずに、function Ship() にて shot[] の末尾へ増設装備ＩＤを突っ込む。機能ブランチ f45 を設けてそこでテスト実装する。

### api_slot_ex の値についての解析情報
データ解析スレ５
http://jbbs.shitaraba.net/bbs/read.cgi/netgame/12394/1416471485/663
```
663 名前：名無し瑞雲≫@アフィ・ロンダ系転載お断り[sage] 投稿日：2015/08/13(木) 02:50:17 ID:.F0JiG/o0
>>661-662
嫁艦とかにもう使ったので確認してきた

使う前：0
使った後（装備なし）：-1
使った後（装備あり）：その装備ID

なぜかこのスロだけ修復中でも変えられる謎

**Comment by hkuno9000** [comment]
増設スロット対応をブランチ f45 にコミットしました.
当方では、まだ増設スロットを付けた艦が居ないので動作未確認です.
テストして問題あればレポートください.

**Comment by yamagen75** [comment]
早速の対応ありがとうございます。
増設スロットの内容表示出来ました。装備スロットの５番目は、-1 が常に入っているんですね…
６番目に追加された、増設スロット内容の表示で無事、応急修理要員が表示出来ました。
戦闘時にも、応急修理要員の表示が確認出来たので問題ないと思います。

**Comment by hkuno9000** [comment]
テストありがとうございました。
無事に動いたとのことなので、ブランチ f45 を master にマージしてpushしました.
