### ISSUE TITLE
2015/11秋イベント対応 - 連合艦隊型「輸送護衛部隊」など

### ISSUE THREAD

**Issue by hkuno9000** [hkuno9000/KanColle-YPS#47]
連合艦隊の新形態「輸送護衛部隊」に対応をする.
https://twitter.com/KanColle_STAFF/status/666947659987578881

* 連合艦隊フラグ値の追加
/api_port/port　の json.api_data.api_combined_flag の値が 1:機動部隊, 2:水上部隊 に加えて
 3:輸送護衛部隊　となる。

* 既存の連合艦隊戦闘パケットに対する追加はない。戦闘進行は従来の1:機動部隊と同じである。
/api_req_combined_battle/battle

対応版をpushしたので、http://hkuno9000.github.io/KanColle-YPS/
からダウンロードするか pull して検証願います。

**Comment by hkuno9000** [comment]
## E-2　の 戦闘結果パケット
"api_landing_hp" がイベント関連情報。api_max_hp, api_now_hp がゲージ, api_sub_value が物資。
/api_req_sortie/battleresult
```
{
  "api_result": 1,
  "api_result_msg": "成功",
  "api_data": {
    "api_ship_id": [-1, 642, 555, 554, 576, 575, 575],
    "api_win_rank": "S",
    "api_get_exp": 250,
    "api_mvp": 1,
    "api_member_lv": "xxxx",
    "api_member_exp": "xxxx",
    "api_get_base_exp": 270,
    "api_get_ship_exp": [-1, 972, 324, 324, 324, 324, 324],
    "api_get_exp_lvup": [
      [490780, 491500, 509000],
      [125843, 127500],
      [72842, 74100],
      [335143, 343400],
      [366095, 369400],
      [340513, 343400]
    ],
    "api_dests": 6,
    "api_destsf": 1,
    "api_lost_flag": [-1, 0, 0, 0, 0, 0, 0],
    "api_quest_name": "コロネハイカラ島沖",
    "api_quest_level": 8,
    "api_enemy_info": {
      "api_level": "",
      "api_rank": "",
      "api_deck_name": "警戒任務群 旗艦艦隊"
    },
    "api_first_clear": 0,
    "api_mapcell_incentive": 0,
    "api_get_flag": [0, 1, 0],
    "api_get_ship": {
      "api_ship_id": 55,
      "api_ship_type": "軽巡洋艦",
      "api_ship_name": "神通",
      "api_ship_getmes": "あの……軽巡洋艦、神通です。<br>どうか、よろしくお願い致します……"
    },
    "api_get_exmap_rate": 0,
    "api_get_exmap_useitem_id": 0,
    "api_landing_hp": {
      "api_max_hp": "320",
      "api_now_hp": "320",
      "api_sub_value": 42
    }
  }
}

**Comment by t-f-m** [comment]
E-3 昼戦戦闘
http://125.6.189.39/kcsapi/api_req_combined_battle/battle

--
`svdata={
  "api_result": 1,
  "api_result_msg": "成功",
  "api_data": {
    "api_deck_id": "1",
    "api_ship_ke": [
      -1,
      529,
      527,
      555,
      622,
      621,
      621
    ],
    "api_ship_lv": [
      -1,
      1,
      1,
      1,
      1,
      1,
      1
    ],
    "api_nowhps": [
      -1,
      40,
      58,
      32,
      32,
      32,
      32,
      98,
      76,
      57,
      43,
      39,
      39
    ],
    "api_maxhps": [
      -1,
      40,
      58,
      32,
      32,
      32,
      32,
      98,
      76,
      57,
      43,
      39,
      39
    ],
    "api_nowhps_combined": [
      -1,
      45,
      44,
      50,
      29,
      31,
      31
    ],
    "api_maxhps_combined": [
      -1,
      45,
      57,
      57,
      32,
      31,
      31
    ],
    "api_midnight_flag": 1,
    "api_eSlot": [
      [
        509,
        509,
        525,
        528,
        -1
      ],
      [
        505,
        506,
        515,
        525,
        -1
      ],
      [
        506,
        525,
        542,
        543,
        -1
      ],
      [
        502,
        502,
        559,
        -1,
        -1
      ],
      [
        502,
        502,
        559,
        -1,
        -1
      ],
      [
        502,
        502,
        559,
        -1,
        -1
      ]
    ],
    "api_eKyouka": [
      [
        0,
        0,
        0,
        0
      ],
      [
        0,
        0,
        0,
        0
      ],
      [
        0,
        0,
        0,
        0
      ],
      [
        0,
        0,
        0,
        0
      ],
      [
        0,
        0,
        0,
        0
      ],
      [
        0,
        0,
        0,
        0
      ]
    ],
    "api_fParam": [
      [
        33,
        0,
        37,
        43
      ],
      [
        77,
        83,
        83,
        79
      ],
      [
        49,
        79,
        49,
        49
      ],
      [
        49,
        79,
        49,
        49
      ],
      [
        49,
        79,
        49,
        49
      ],
      [
        49,
        79,
        49,
        49
      ]
    ],
    "api_eParam": [
      [
        90,
        0,
        80,
        99
      ],
      [
        68,
        48,
        40,
        70
      ],
      [
        48,
        80,
        30,
        39
      ],
      [
        58,
        88,
        44,
        36
      ],
      [
        48,
        76,
        40,
        30
      ],
      [
        48,
        76,
        40,
        30
      ]
    ],
    "api_fParam_combined": [
      [
        56,
        94,
        78,
        68
      ],
      [
        85,
        86,
        70,
        78
      ],
      [
        77,
        84,
        106,
        78
      ],
      [
        59,
        89,
        59,
        59
      ],
      [
        50,
        84,
        79,
        51
      ],
      [
        57,
        84,
        72,
        52
      ]
    ],
    "api_search": [
      1,
      1
    ],
    "api_formation": [
      "14",
      1,
      2
    ],
    "api_stage_flag": [
      1,
      0,
      0
    ],
    "api_kouku": {
      "api_plane_from": [
        [
          1
        ],
        [
          -1
        ]
      ],
      "api_stage1": {
        "api_f_count": 16,
        "api_f_lostcount": 0,
        "api_e_count": 0,
        "api_e_lostcount": 0,
        "api_disp_seiku": 1,
        "api_touch_plane": [
          -1,
          -1
        ]
      },
      "api_stage2": null,
      "api_stage3": null,
      "api_stage3_combined": null
    },
    "api_support_flag": 0,
    "api_support_info": null,
    "api_opening_flag": 1,
    "api_opening_atack": {
      "api_frai": [
        -1,
        6,
        0,
        0,
        0,
        0,
        0
      ],
      "api_erai": [
        -1,
        0,
        0,
        0,
        0,
        0,
        0
      ],
      "api_fdam": [
        -1,
        0,
        0,
        0,
        0,
        0,
        0
      ],
      "api_edam": [
        -1,
        0,
        0,
        0,
        0,
        0,
        45
      ],
      "api_fydam": [
        -1,
        45,
        0,
        0,
        0,
        0,
        0
      ],
      "api_eydam": [
        -1,
        0,
        0,
        0,
        0,
        0,
        0
      ],
      "api_fcl": [
        -1,
        1,
        0,
        0,
        0,
        0,
        0
      ],
      "api_ecl": [
        -1,
        0,
        0,
        0,
        0,
        0,
        0
      ]
    },
    "api_hourai_flag": [
      1,
      1,
      1,
      1
    ],
    "api_hougeki1": {
      "api_at_list": [
        -1,
        3,
        7,
        1,
        2,
        6,
        10,
        4,
        11,
        5
      ],
      "api_at_type": [
        -1,
        2,
        0,
        0,
        2,
        0,
        0,
        0,
        0,
        0
      ],
      "api_df_list": [
        -1,
        [
          9,
          9
        ],
        [
          5
        ],
        [
          7
        ],
        [
          8,
          8
        ],
        [
          10
        ],
        [
          4
        ],
        [
          11
        ],
        [
          4
        ],
        [
          10
        ]
      ],
      "api_si_list": [
        -1,
        [
          90,
          90
        ],
        [
          509
        ],
        [
          123
        ],
        [
          90,
          90
        ],
        [
          -1
        ],
        [
          502
        ],
        [
          -1
        ],
        [
          502
        ],
        [
          -1
        ]
      ],
      "api_cl_list": [
        -1,
        [
          1,
          1
        ],
        [
          0
        ],
        [
          1
        ],
        [
          1,
          1
        ],
        [
          0
        ],
        [
          0
        ],
        [
          0
        ],
        [
          0
        ],
        [
          0
        ]
      ],
      "api_damage": [
        -1,
        [
          5,
          71
        ],
        [
          0
        ],
        [
          10
        ],
        [
          50.1,
          38.1
        ],
        [
          0
        ],
        [
          0
        ],
        [
          0
        ],
        [
          0
        ],
        [
          0
        ]
      ]
    },
    "api_raigeki": {
      "api_frai": [
        -1,
        5,
        1,
        1,
        1,
        5,
        4
      ],
      "api_erai": [
        -1,
        0,
        0,
        0,
        6,
        3,
        0
      ],
      "api_fdam": [
        -1,
        0,
        0,
        1,
        0,
        0,
        18
      ],
      "api_edam": [
        -1,
        37,
        0,
        0,
        62,
        108,
        0
      ],
      "api_fydam": [
        -1,
        56,
        11,
        9,
        17,
        52,
        62
      ],
      "api_eydam": [
        -1,
        0,
        0,
        0,
        18,
        1,
        0
      ],
      "api_fcl": [
        -1,
        1,
        1,
        1,
        1,
        1,
        1
      ],
      "api_ecl": [
        -1,
        0,
        0,
        0,
        1,
        1,
        0
      ]
    },
    "api_hougeki2": {
      "api_at_list": [
        -1,
        2,
        7,
        5,
        3,
        4,
        6,
        1
      ],
      "api_at_type": [
        -1,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ],
      "api_df_list": [
        -1,
        [
          7
        ],
        [
          2
        ],
        [
          7
        ],
        [
          7
        ],
        [
          7
        ],
        [
          7
        ],
        [
          7
        ]
      ],
      "api_si_list": [
        -1,
        [
          50
        ],
        [
          509
        ],
        [
          -1
        ],
        [
          -1
        ],
        [
          -1
        ],
        [
          -1
        ],
        [
          -1
        ]
      ],
      "api_cl_list": [
        -1,
        [
          1
        ],
        [
          1
        ],
        [
          1
        ],
        [
          1
        ],
        [
          0
        ],
        [
          2
        ],
        [
          0
        ]
      ],
      "api_damage": [
        -1,
        [
          6
        ],
        [
          3.1
        ],
        [
          3
        ],
        [
          2
        ],
        [
          0
        ],
        [
          3
        ],
        [
          0
        ]
      ]
    },
    "api_hougeki3": {
      "api_at_list": [
        -1,
        1,
        7,
        2,
        3,
        4,
        5,
        6
      ],
      "api_at_type": [
        -1,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ],
      "api_df_list": [
        -1,
        [
          7
        ],
        [
          6
        ],
        [
          7
        ],
        [
          7
        ],
        [
          7
        ],
        [
          7
        ],
        [
          7
        ]
      ],
      "api_si_list": [
        -1,
        [
          -1
        ],
        [
          509
        ],
        [
          50
        ],
        [
          -1
        ],
        [
          -1
        ],
        [
          -1
        ],
        [
          -1
        ]
      ],
      "api_cl_list": [
        -1,
        [
          1
        ],
        [
          2
        ],
        [
          1
        ],
        [
          0
        ],
        [
          1
        ],
        [
          1
        ],
        [
          1
        ]
      ],
      "api_damage": [
        -1,
        [
          3
        ],
        [
          17
        ],
        [
          14
        ],
        [
          0
        ],
        [
          1
        ],
        [
          2
        ],
        [
          2
        ]
      ]
    }
  }
}`

**Comment by t-f-m** [comment]
portから抜粋
--
```
    "api_combined_flag": 3,
```
--
現状、第二艦隊の昼戦の攻防が反映されていません。

**Comment by hkuno9000** [comment]
@t-f-m E3の戦闘パケット情報ありがとうございます。
情報を元に修正版をpushしました。これで動作するか確認願います。

**Comment by t-f-m** [comment]
特に問題なく動作しているように見えます。確認が要るとすれば夜戦マスのAPIくらいでしょうか。
