### ISSUE TITLE
勝敗判定条件

### ISSUE THREAD

**Issue by hkuno9000** [hkuno9000/KanColle-YPS#61]
KanColle-YPS は、 [wiki情報の勝利条件](http://wikiwiki.jp/kancolle/?%BE%A1%CD%F8%BE%F2%B7%EF)を参考にして、戦闘データの自ダメージと敵ダメージから、勝敗判定を推定して戦況画面の「勝敗推定」欄に表示している。その判定式は次の通りである。
wiki情報とは小数点丸めやC/D/E判定が異なるが、Issue #10, #20, #24 の検証例を正しく判定できており、その後のプレイでも判定ミスは発生していない。
なお、空襲戦の勝敗判定条件は Issue #50 で別途扱う。
## 勝敗判定条件 2018/5/11版(v1.8.2pre)

艦隊HP値 ::= 昼戦開始時点の各艦HP値の合計 ※艦の最大HP値ではない.
艦隊ダメージ値 ::= 昼戦開始時点から戦闘終了までの各艦HP減少値の合計
艦隊ダメージ率 ::= `floor(100 * 艦隊ダメージ値 / 艦隊HP値)` ※少数点以下切り捨ての百分率値
- 完全S: 敵全隻撃沈かつ、自轟沈なしかつ、自艦隊ダメージ値0 ※ダメージ率にあらず
- S勝利: 敵全隻撃沈かつ、自轟沈なし
- A勝利: 敵艦隊2/3隻(少数切り捨て)以上撃沈かつ、自轟沈なし
- B勝利: 敵旗艦撃沈かつ、自轟沈数より敵撃沈数が多い
- D敗北: 自艦隊単艦かつ旗艦大破
- B勝利: `敵艦隊ダメージ率 * 10`が、`自艦隊ダメージ率 * 25` より大きい ※戦果ゲージ比が2.5より大きい
- C敗北: `敵艦隊ダメージ率 * 10`が、`自艦隊ダメージ率 * 9` より大きい ※戦果ゲージ比が0.9より大きい
- D敗北: 敵旗艦撃沈、または自轟沈なし、または自艦隊に旗艦以外の生存艦あり
- E敗北: 上記以外、つまり敵旗艦生存かつ自艦隊旗艦以外轟沈
- ※敵艦隊ダメージ率0かつ自艦隊ダメージ率0ならC敗北条件を満たさないのでD敗北となる.
- ※敵艦隊ダメージ率1以上かつ自艦隊ダメージ率0ならB勝利条件(2.5倍より大)を満たすのでB勝利となる.
- ※全ての計算は小数切り捨てとする. 四捨五入はしない.

``` javascript
var f_damage_percent = Math.floor(100 * f_damage_total / f_hp_total); // 自艦隊ダメージ百分率. 小数点以下切り捨て.
var e_damage_percent = Math.floor(100 * e_damage_total / e_hp_total); // 敵艦隊ダメージ百分率. 小数点以下切り捨て.
if (e_count == e_lost_count && f_lost_count == 0) {
    return (f_damage_total == 0) ? '完S' : 'S';    // 1%未満の微ダメージでも、"完S"にはならない.
}
if (e_lost_count > 0 && e_lost_count >= Math.floor(e_count * 2 / 3) && f_lost_count == 0) { // 確定.
    return 'A';
}
if (e_leader_lost && f_lost_count < e_lost_count) {　// 検証中!!! 敵旗艦撃沈かつ、自轟沈数より敵撃沈数が多いならば、B勝利.
    return 'B';
}
if (f_count == 1 && (f_hp_total - f_damage_total) / f_maxhp_total <= 0.25) { // 検証中!!! 自艦隊単艦かつ旗艦大破ならば、D敗北.
    ///@see https://github.com/andanteyk/ElectronicObserver/commit/80fc664e3d5c4223dd585882a726ecc719d15be8
    return 'D';
}
if (10 * e_damage_percent > 25 * f_damage_percent) { // 確定. 戦果ゲージ比が2.5より大きいならば、B勝利.
    return 'B';
}
if (10 * e_damage_percent > 9 * f_damage_percent) { // 確定. 戦果ゲージ比が0.9より大きいならば、C敗北.
    return 'C';
}
if (e_leader_lost || f_lost_count == 0 || f_count - f_lost_count > 1) {　// 検証中!!! 敵旗艦撃沈、または自轟沈なし、または自艦隊に旗艦以外の生存艦ありならば、D敗北.
    return 'D';
}
return 'E'; // 検証中!!! 上記以外、つまり敵旗艦生存かつ自艦隊旗艦以外轟沈ならば、E敗北.
```
## 戦闘中にダメコン発動した場合のHP値
- 修理要員発動では、艦の最大HPの20%に回復する(小数点以下切り捨て)
- 修理女神発動では、艦の最大HPに回復する

修理発動後は、夜戦終了まで轟沈保護となり、攻撃を受けてもHP1以下にはならない。
## 依頼

判定ミスは、KanColle-YPSの「記録」欄に蓄積されます。
MISS判定が見つかれば、それをコメントとして貼ってください。

**Comment by hkuno9000** [comment]
演習相手:x, f_damage:101/335(30%)[0/6]357, e_damage:100/365(27%)[0/6], rate:0.9, rank:D
これで、C/D判定閾値が確定した

**Comment by hkuno9000** [comment]
A勝利: 敵艦隊６隻かつ、４隻以上撃沈かつ、自轟沈なし
A勝利: 敵艦隊５隻以下かつ、半数以上撃沈かつ、自轟沈なし
この条件を素直にコーディングしたのが下記の現状コード
```
if (e_lost_count >= (e_count == 6 ? 4 : e_count/2) && f_lost_count == 0) {
    return 'A';
}
```
wiki情報の下記コメント
> A勝利条件が、「半数以上撃沈」となっていますが、「敵2隻以上で、2/3以上(小数点以下切り捨て)撃沈」と考えることもできます。 -- 2016-03-15 (火) 21:03:48

をコード化すると下記になる。こちらでも同じ結果が得られる。
```
if (e_lost_count >= Math.floor(e_count * 2 / 3) && f_lost_count == 0) {
    return 'A';
}
```
艦これサーバ内の勝敗判定はたぶんコレだろう。
ダメージ率も小数点以下切り捨てで判定が一致することをふまえると、サーバの演算処理は小数点以下切り捨てを行う整数演算だと思われる。

**Comment by hkuno9000** [comment]
[E敗北のスクリーンショット](https://gyazo.com/08c9ec04b04737eb6d6d174a892dfdd4)

### 戦況ログ
2016/8/11 13:17:46, server:2016/8/11 13:17:47
サブ島沖海域 battle1

5-3-1:気のせいだった
5-3-3
単縦/同航/敵単縦
戦闘被害:f_damage:15/21(71%)[2/3]48, e_damage:35/352(9%)[0/6], api:/api_req_battle_midnight/sp_midnight, rate:0.1268
勝敗推定:E
戦闘詳報  ＋
friend damage
南西オリョール巡回
1(時津風Lv23).	6/16(-10):中破
2(初春Lv2).	0/16(-129):撃沈---
3(不知火Lv2).	0/16(-433):撃沈---
被撃墜数: 0
enemy damage
1(軽巡ヘ級flagshipLv1).	57/57:*	＋
2(重巡リ級flagshipLv1).	76/76:*	＋
3(重巡リ級flagshipLv1).	41/76(-35):小破	＋
4(雷巡チ級eliteLv1).	50/50:*	＋
5(雷巡チ級eliteLv1).	50/50:*	＋
6(駆逐ロ級flagshipLv1).	43/43:*	＋

**Comment by hkuno9000** [comment]
D/E判定ミス
[画像](https://gyazo.com/9734c4607385eed7c898b4c671f69828)
## 戦況ログ
2016/8/11 14:57:05, server:2016/8/11 14:57:05
サーモン海域北方 battle1

5-5-2
単縦/Ｔ字不利/敵複縦
索敵: なし
制空権喪失
戦闘被害:f_damage:45/47(95%)[4/6]100, e_damage:0/504(0%)[0/6], api:/api_req_sortie/battle, rate:0
勝敗推定:E
戦闘詳報  ＋
friend damage
E敗北検証艦隊
1(島風Lv18).	1/19(-15):大破!!!
2(朧Lv3).	0/15(-47):撃沈---
3(白雪Lv3).	0/15(-136):撃沈---
4(睦月Lv2).	0/13(-79):撃沈---
5(望月Lv2).	0/13(-35):撃沈---
6(多摩Lv1).	1/25(-24):大破!!!
被撃墜数: 0
enemy damage
1(戦艦レ級Lv1).	180/180:*	＋
2(軽母ヌ級flagshipLv1).	84/84:*	＋
3(軽母ヌ級flagshipLv1).	84/84:*	＋
4(重巡リ級eliteLv1).	60/60:*	＋
5(軽巡ヘ級flagshipLv1).	57/57:*	＋
6(駆逐イ級flagshipLv1).	39/39:*	＋
battle result
敵前衛警戒部隊(0/6):D
勝敗推定ミス f_damage:45/47(95%)[4/6]100, e_damage:0/504(0%)[0/6], api:/api_req_sortie/battle, rate:0, f_lost:4, e_lost:0, rank:D/E MISS!!
MVP: 島風Lv18 +945exp
LOST: 朧Lv3
LOST: 白雪Lv3
LOST: 睦月Lv2
LOST: 望月Lv2

**Comment by hkuno9000** [comment]
[D/E敗北判定ミス](https://gyazo.com/9734c4607385eed7c898b4c671f69828)

## 戦況ログ
2016/8/11 14:57:05, server:2016/8/11 14:57:05
サーモン海域北方 battle1

5-5-2
単縦/Ｔ字不利/敵複縦
索敵: なし
制空権喪失
戦闘被害:f_damage:45/47(95%)[4/6]100, e_damage:0/504(0%)[0/6], api:/api_req_sortie/battle, rate:0
勝敗推定:E
戦闘詳報  ＋
friend damage
E敗北検証艦隊
1(島風Lv18).	1/19(-15):大破!!!
2(朧Lv3).	0/15(-47):撃沈---
3(白雪Lv3).	0/15(-136):撃沈---
4(睦月Lv2).	0/13(-79):撃沈---
5(望月Lv2).	0/13(-35):撃沈---
6(多摩Lv1).	1/25(-24):大破!!!
被撃墜数: 0
enemy damage
1(戦艦レ級Lv1).	180/180:*	＋
2(軽母ヌ級flagshipLv1).	84/84:*	＋
3(軽母ヌ級flagshipLv1).	84/84:*	＋
4(重巡リ級eliteLv1).	60/60:*	＋
5(軽巡ヘ級flagshipLv1).	57/57:*	＋
6(駆逐イ級flagshipLv1).	39/39:*	＋
battle result
敵前衛警戒部隊(0/6):D
勝敗推定ミス f_damage:45/47(95%)[4/6]100, e_damage:0/504(0%)[0/6], api:/api_req_sortie/battle, rate:0, f_lost:4, e_lost:0, rank:D/E MISS!!
MVP: 島風Lv18 +945exp
LOST: 朧Lv3
LOST: 白雪Lv3
LOST: 睦月Lv2
LOST: 望月Lv2

**Comment by hkuno9000** [comment]
[E敗北](https://gyazo.com/9404eaad8c2e4f094d11584bae26547c)
2016/8/11 16:00:11, server:2016/8/11 16:00:12
サーモン海域北方 battle1

5-5-2
単縦/同航/敵輪形
索敵: なし
制空権喪失
戦闘被害:f_damage:74/75(98%)[1/2]87, e_damage:16/471(3%)[0/6], api:/api_req_sortie/battle, rate:0.0306
勝敗推定:E
戦闘詳報  ＋
friend damage
E敗北検証艦隊
1(伊勢Lv1).	1/74(-73):大破!!!
2(三日月Lv3).	0/13(-34):撃沈---
被撃墜数: 0
enemy damage
1(戦艦レ級Lv1).	180/180:*	＋
2(軽母ヌ級flagshipLv1).	84/84:*	＋
3(軽母ヌ級flagshipLv1).	84/84:*	＋
4(軽巡ヘ級flagshipLv1).	57/57:*	＋
5(駆逐イ級flagshipLv1).	25/39(-14):小破	＋
6(潜水カ級eliteLv50).	25/27(-2):.	＋
battle result
敵前衛警戒部隊(0/6):E
LOST: 三日月Lv3

**Comment by hkuno9000** [comment]
自艦隊旗艦以外轟沈でも敵旗艦を撃沈すればB勝利
[B勝利](https://gyazo.com/997a09358b7e1a82a5671519ba09e001)
キス島沖 battle1

3-2-2
単縦/同航/敵複縦
索敵: 敵艦隊発見!
制空権確保
戦闘被害:f_damage:28/98(28%)[1/2]112, e_damage:100/233(42%)[x2/6], api:/api_req_sortie/battle, rate:1.5
勝敗推定:B
戦闘詳報  ＋
friend damage
E敗北検証艦隊
1(Bismarck dreiLv99).	70/96(-26):小破
2(霞Lv4).	0/16(-12):撃沈---
被撃墜数: 0
enemy damage
1(雷巡チ級eliteLv1).	0/50(-113):撃沈---	＋
2(雷巡チ級Lv1).	0/48(-120):撃沈---	＋
3(雷巡チ級Lv1).	48/48:*	＋
4(駆逐ロ級flagshipLv1).	43/43:*	＋
5(駆逐ロ級Lv1).	20/22(-2):.	＋
6(駆逐ロ級Lv1).	22/22:*	＋
battle result
敵水雷戦隊(2/6):B
MVP: Bismarck dreiLv99 +960exp
LOST: 霞Lv4

**Comment by hkuno9000** [comment]
自艦隊旗艦以外轟沈でも、敵旗艦撃沈ならC敗北となる
[C敗北](https://gyazo.com/6d32b8e7878299cc34f4b69c988d0a28)
キス島沖 battle1

3-2-2
単縦/反航/敵単縦
索敵: 敵艦隊発見!
制空権確保
戦闘被害:f_damage:44/103(42%)[3/4]139, e_damage:100/211(47%)[x3/6], api:/api_req_sortie/battle, rate:1.119
勝敗推定:C
戦闘詳報  ＋
friend damage
E敗北検証艦隊
1(Bismarck dreiLv99).	59/96(-37):小破
2(菊月Lv3).	0/13(-12):撃沈---
3(電Lv3).	0/15(-28):撃沈---
4(響Lv3).	0/15(-4):撃沈---
被撃墜数: 0
enemy damage
1(軽巡ホ級flagshipLv1).	0/53(-77):撃沈---	＋
2(雷巡チ級eliteLv1).	50/50:*	＋
3(駆逐ハ級eliteLv1).	40/40:*	＋
4(駆逐ハ級Lv1).	21/24(-3):.	＋
5(駆逐ロ級Lv1).	0/22(-24):撃沈---	＋
6(駆逐ロ級Lv1).	0/22(-110):撃沈---	＋
battle result
敵水雷戦隊(3/6):C
MVP: Bismarck dreiLv99 +768exp
LOST: 菊月Lv3
LOST: 電Lv3
LOST: 響Lv3

**Comment by hkuno9000** [comment]
[D敗北: 自艦隊6隻中轟沈4, 敵5隻中撃沈1(敵旗艦含まず)](https://gyazo.com/3983904bae22144ac3e7b3351f2c2f0e)

キス島沖 battle1

3-2-2
単縦/同航/敵単縦
索敵: なし
制空権確保
戦闘被害:f_damage:12/54(22%)[4/6]123, e_damage:26/145(17%)[1/5], api:/api_req_sortie/battle, rate:0.7727
勝敗推定:D
戦闘詳報  ＋
friend damage
E敗北検証艦隊
1(愛宕Lv2).	40/45(-5):.
2(村雨Lv3).	0/16(-7):撃沈---
3(電Lv3).	0/15(-11):撃沈---
4(敷波Lv2).	0/15(-44):撃沈---
5(夕立Lv3).	0/16(-109):撃沈---
6(霞Lv2).	2/16:大破!!!
被撃墜数: 0
enemy damage
1(軽巡ホ級flagshipLv1).	53/53:*	＋
2(駆逐ハ級Lv1).	24/24:*	＋
3(駆逐ハ級Lv1).	0/24(-39):撃沈---	＋
4(駆逐ロ級Lv1).	22/22:*	＋
5(駆逐ロ級Lv1).	20/22(-2):.	＋
battle result
敵水雷戦隊(1/5):D
MVP: 愛宕Lv2 +672exp
LOST: 村雨Lv3
LOST: 電Lv3
LOST: 敷波Lv2
LOST: 夕立Lv3

**Comment by skywalker999u** [comment]
![guesswinrankmiss1](https://user-images.githubusercontent.com/20737603/33415611-ebdc6bfa-d5da-11e7-802c-ce597ef66549.PNG)

(sorry that I am using another extension (a fork of this project, unsupported for quite some time), but since they share the same codes for calculation, I think I might contribute info here...

**Comment by hkuno9000** [comment]
@skywalker999u 単艦艦隊のD敗北判定ミスを修正しました。

**Comment by hkuno9000** [comment]
２年間、誤判定は出ていない。
勝敗判定条件は現状使用で正しいと結論する。
