### ISSUE TITLE
連合艦隊夜戦の api_active_deck で夜戦参加艦隊を示す

### ISSUE THREAD

**Issue by SkyRavenHK** [hkuno9000/KanColle-YPS#77]
in function on_battle(), d.api_active_deck: [friendly_active_deck, enemy_active_deck] shows the decks used in night battle
the value of frienly_active_deck and enemy_active_deck can only be 1 or 2,
1 indicates main fleet participating in night battle (自軍第一艦隊 1..6 / 敵軍通常艦隊 7..12)
2 indicates escort fleet participating in night battle (自軍第二艦隊 -1..-6 / 敵軍護衛艦隊 -7..-12)
e.g. when 自軍第二艦隊 vs 敵軍通常艦隊, api_active_deck = [2,1]
(sorry that my Japanese is not good enough to express this :(
(btw i am skywalker999u who did a pull request before, but i used the wrong account to file this as i use this ac to contribute on updating a fork of this project (KanColleRaiseSup)

**Comment by hkuno9000** [comment]
@SkyRavenHK 
Thx report. On #64 (6-5boss: 6-friend vs 12-enemy), We had a discussion about "api_active_deck".
I am tring to support them.

**Comment by hkuno9000** [comment]
@SkyRavenHK 
I have supported "api_active_deck" on v1.5.6
please check it.

**Comment by SkyRavenHK** [comment]
@hkuno9000
it seemed that the code has only applied on the attacker part but not the target part
i modded that part on my local copy for testing
will report back if i have chance to face enemy escort fleet in night battle again

**Comment by hkuno9000** [comment]
oh, I have mistaken. I will make a patch ASAP.

**Comment by hkuno9000** [comment]
@SkyRavenHK 
I have fixed target part, and push them on v1.5.7.

**Comment by SkyRavenHK** [comment]
@hkuno9000 
正確に作動できたと確認しました。ありがとうございました。
