### ISSUE TITLE
(対敵連合艦隊) 支援艦隊砲雷撃 api_damage.length==13は可能

### ISSUE THREAD

**Issue by SkyRavenHK** [hkuno9000/KanColle-YPS#78]
as mentioned in title.
enemy combined fleet has 12 elements, therefore (naturally) var i should reach beyond 6 in that case.

**Comment by hkuno9000** [comment]
@SkyRavenHK 
fix "api_damage.length==13" cases at v1.5.6 testing
please check it, and close this issue if you has no bug. or report me the bug.
