### ISSUE TITLE
改修工廠の装備リストを学習して改修可能な一覧を表示する

### ISSUE THREAD

**Issue by hkuno9000** [hkuno9000/KanColle-YPS#84]
## 機能
改修工廠メニュー操作時にサーバから降りてくるAPIから改修パラメタを抜き出して曜日別に保存し、
当日の改修できる保有装備の一覧と、改修パラメタを表示する。

## 作成するデータ構造
$remodel_slotlist  = { 改修レシピID値 ： { 改修パラメタ  } , ... }
$remodel_slotweek = { 曜日値 : { 改修レシピID値 : 二番艦名ID, ...}, .... }
改修レシピID値をキーとしたマップ、曜日値をキーとしたマップを作成する

## 改修工廠メニューAPI:  /api_req_kousyou/remodel_slotlist
曜日と二番艦によって３つの改修可能装備が提示される。消費資材と消費装備のデータもここで得られるように見えるが、消費装備メンバの値は０固定である。
```json
svdata={"api_result":1,"api_result_msg":"\u6210\u529f","api_data":[{"api_id":152,"api_slot_id":10,"api_req_fuel":10,"api_req_bull":40,"api_req_steel":70,"api_req_bauxite":20,"api_req_buildkit":2,"api_req_remodelkit":2,"api_req_slot_id":0,"api_req_slot_num":0},{"api_id":201,"api_slot_id":4,"api_req_fuel":10,"api_req_bull":50,"api_req_steel":80,"api_req_bauxite":0,"api_req_buildkit":1,"api_req_remodelkit":1,"api_req_slot_id":0,"api_req_slot_num":0},{"api_id":301,"api_slot_id":14,"api_req_fuel":70,"api_req_bull":100,"api_req_steel":70,"api_req_bauxite":20,"api_req_buildkit":1,"api_req_remodelkit":1,"api_req_slot_id":0,"api_req_slot_num":0}]}
```
## 改修装備選択API:  /api_req_kousyou/remodel_slotlist_detail
改修対象装備を選ぶと、確実化の開発・改修資材数と、消費装備のデータが得られる。
改修対象の改修レベルによってデータ値は異なる。（★６以上、★max)
```json
svdata={"api_result":1,"api_result_msg":"\u6210\u529f","api_data":{"api_req_buildkit":2,"api_req_remodelkit":2,"api_certain_buildkit":4,"api_certain_remodelkit":3,"api_req_slot_id":20,"api_req_slot_num":2,"api_change_flag":0}}

**Comment by hkuno9000** [comment]
commit 7e206b4 にて暫定実装した。

### TODO
* 一覧の並びが「改修レシピID値」順（改修メニューの上中下順）で見辛い。装備種類の順に並べたい。
* 同一装備に対して「改修レシピID」が複数がある。二番艦が異なると別IDになるようだ。maxからの装備転換に備えるためだと思うが、重複が煩わしい。

**Comment by t-f-m** [comment]
随伴艦なしのケースで動作していないようです。

**Comment by hkuno9000** [comment]
@t-f-m バグ出し感謝です。修正しました。
