### ISSUE TITLE
航空母艦カットイン攻撃に対応する

### ISSUE THREAD

**Issue by hkuno9000** [hkuno9000/KanColle-YPS#92]
https://twitter.com/KanColle_STAFF/status/907575817852424192
> 19▼航空母艦「戦爆連合」カットイン攻撃の実装
航空母艦の運用する艦載機の構成によって、昼間戦闘において、航空母艦が艦載機による通常より効果の高い攻撃を繰り出すカットイン攻撃が実装されました。※敵深海棲艦は、現在は最前線周辺の一部精強空母のみ、同攻撃が行えます。

battle_api.api_at_type[n] に値 7 が追加された。これが昼間戦闘の「戦爆連合カットイン」である。

https://twitter.com/KanColle_STAFF/status/907576774967533568
> 20▼航空母艦カットイン攻撃の補足
※夜間作戦用航空母艦、または装備等によって夜間作戦能力を持った空母は、搭載機の構成によって、夜襲カットイン攻撃を行う場合があります。
※本日実装が開始された「航空母艦カットイン攻撃」は、今後内容及び種類等が更新されていく予定です。

battle_api.api_sp_list[n] に値が増えていると予想される。データ提供求む。

**Comment by skywalker999u** [comment]
空母の夜襲カットインはbattle_sp_nameのcase 6になっています。

**Comment by hkuno9000** [comment]
@skywalker999u 情報提供ありがとうございます。
対応修正をpushしました。問題ないかご確認ください。

**Comment by skywalker999u** [comment]
@hkuno9000 
正確に動作していること確認しました。
対応修正ありがとうございました。
